Add function to get proxy dicts for Requests
Justintime50/proxlist pull request #2
Opened 2021-12-07 06:53 UTC by nwithan8

2021-12-07 07:31 UTC, nwithan8 commented
Unsure if HTTPS needed

2021-12-07 07:48 UTC, Justintime50 requested changes
Thanks for the contribution @nwithan8! This is a nice utility helper. I have some thoughts (I hold my open source to an incredibly high standard, I apologize if some of this is a bit much).

1. Can we add a test function for this under `/test/unit/test_proxies.py`?
2. `https` here is definitely needed, let's keep it. (answering your other question)
3. Nit: I like to assign my return values to a variable so I can return a clean variable. Can we also add a line-break between the return statement and whatever came before it? Makes the code read really nice. Finally, let's maybe add a doctoring here describing what the intended use of this function is as it may not be immediately understood by others. Something such as "Returns a proxies dictionary, perfect for passing into the `requests` proxies parameter" or something to that affect.
4. We'll then want to document this in the README.
5. Finally, we'll want to add this function to the `__init__.py` file imports and include it in the `__all__` variable so users can easily use this once they've imported this package.

2021-12-07 07:48 UTC, Justintime50 commented on proxlist/proxies.py
> +def proxy_dict() -> dict:
```suggestion
def proxy_dict() -> Dict[str, str]:
```

2021-12-07 07:48 UTC, Justintime50 commented on proxlist/proxies.py
> +def proxy_dict() -> dict:
For Python to be happy with type hints on Python prior to 3.9, you'll want to add `from typing import Dict` to the top.

2021-12-07 08:13 UTC, nwithan8 commented
1. []
2. [x]
3. []
4. []
5. []

2021-12-07 15:05 UTC, Justintime50 requested changes

2021-12-07 15:05 UTC, Justintime50 commented on proxlist/proxies.py
> +    :rtype: dict
No need for this line since we have type hinting

2021-12-07 15:05 UTC, Justintime50 commented on proxlist/proxies.py
> +    Returns a proxy dictionary, perfect for passing into the requests `proxies` parameter
This should be on the same line as the opening quotes

2021-12-07 15:05 UTC, Justintime50 commented on proxlist/proxies.py
> +        'https': f'https://{proxy}',
```suggestion
        'https': f'http://{proxy}',
```

2021-12-07 15:05 UTC, Justintime50 commented on test/unit/test_proxies.py
> +    http = proxy_dict.get('http', None)
```suggestion
    http = proxy_dict.get('http')
```
None is the implicit default here, no need to include

2021-12-07 15:05 UTC, Justintime50 commented on test/unit/test_proxies.py
> +
No need for two line breaks, one will do

2021-12-07 16:43 UTC, Justintime50 commented
Looks like the build also failed. You'll want to run `make black` on the project to format it correctly.

2021-12-07 16:44 UTC, Justintime50 commented on test/unit/test_proxies.py
> +    http = proxy_dict.get('http', None)
Same with the one below it.

2021-12-08 05:26 UTC, Justintime50 commented
You'll want to rebase this against the `main` branch as I've pushed changes since this PR.

2021-12-08 21:42 UTC, Justintime50 commented
The `main` branch has diverged so far from this at this point.

I think I'm going to close this as `wontfix` only because I want to keep the library generic, the proxy dictionary although nice is tailored to a `requests` context, the syntax may not always be the same depending on the HTTP library in use.

2021-12-08 21:42 UTC, closed without merging